import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import BlogPost from '@/components/BlogCard';

import { GraphQLClient, gql } from 'graphql-request';

const graphcms = new GraphQLClient(
  'https://us-west-2.cdn.hygraph.com/content/cldmeipsv15gy01rq0daid6jt/master'
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        publishedAt
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  console.log(posts);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {posts.map((post) => (
          <BlogPost key={post.id} {...post} />
        ))}
      </main>
    </>
  );
}
